# site settings
title: Good Times
subtitle: Cool Places
email: goodtimescoolplaces@gmail.com
description: We discover the world's unforgettable spots, unique experiences, & hidden gems.
baseurl: "/goodtimescoolplaces" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
phone: http://wa.me/35699741668
formspree: f/xldjdbzj

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
socials:
  Instagram: https://www.instagram.com/goodtimescoolplaces
  WhatsApp: http://wa.me/35699741668
  Twitter: http://x.com/goodtimescoolp
  Youtube: https://www.youtube.com/@goodtimescoolplaces
  Facebook: https://www.facebook.com/share/CwoL2WPhEyk3qG8M/?mibextid=LQQJ4d
  Snapchat: https://snapchat.com/t/D4jXI4GH
  Pinterest: https://pin.it/3NHxhZNaC
  Tumblr: https://www.tumblr.com/goodtimescoolplaces


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- README.md 
